CREATE TABLE "user" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"auth_uid" text NOT NULL,
	"plate_number" text,
	"email" text,
	CONSTRAINT "user_anon_id_key" UNIQUE("auth_uid")
);
